name: Build_Webserver

on:
  workflow_run:
    workflows: ["Build_TUI"]
    types:
      - completed
  push:
    branches:
      - "release/*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-musl
          - os: ubuntu-22.04
            target: aarch64-unknown-linux-gnu
          # macOS
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Show Rust version
        run: |
          rustc -Vv
          cargo -V

      - name: Set release version
        run: echo "brc=${GITHUB_REF##refs/heads/release/}" >> $GITHUB_ENV

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install cross for ARM builds
        if: contains(matrix.target, 'aarch64')
        run: cargo install cross --force

      - name: pnpm install
        run: npm install -g pnpm
      - name: build dist
        run: cd webview && pnpm install && npm run build:socket
        
      - name: Build
        shell: bash
        run: |
          echo "Building for target ${{ matrix.target }}"
          if [[ "${{ matrix.target }}" == *"aarch64"* ]]; then
            cross build --release -p pcap-web --target ${{ matrix.target }}
          else
            cargo build --release -p pcap-web --target ${{ matrix.target }}
          fi

      - name: Prepare release folder
        shell: bash
        run: |
          mkdir -p release
          mv target/${{ matrix.target }}/release/pcap-web release/pcap-web-${{ matrix.target }}

      - name: Set release version
        run: echo "brc=${GITHUB_REF##refs/heads/release/}" >> $GITHUB_ENV
        shell: bash
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: ${{ env.brc }}
          files: release/pcap-web-${{ matrix.target }}
          allow_updates: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
